<?php
		define('TWITTER_USER_TIMELINE_USER','QuanticaLabs');
		define('TWITTER_USER_TIMELINE_COUNT','5');
		
		define('TWITTER_USER_TIMELINE_CONSUMER_KEY','fwPrqDm5vHQPet8iBn1ttA');
		define('TWITTER_USER_TIMELINE_CONSUMER_SECRET','1Ra1OUD7xjCOVSp1AciHVxou6IENYiY0SGZVeRNsw');
		define('TWITTER_USER_TIMELINE_ACCESS_TOKEN','189566126-M0553Nv3qsWn137ymR0KsRfciK5H2FnR9zeFhRu4');
		define('TWITTER_USER_TIMELINE_ACCESS_TOKEN_SECRET','xuFGGXFD2ldKBcJhFmdnNBHFQyxNu7ETGa1CXF4S5mI');